# Detect useless polymorfphisms

In this notebook the oryginal dataset is analyzed and we detect (and remove from further analysis) polymorphisms that has no ability to differentiate between eyes colors.

### Transform source files to csv

In [1]:
PED_FILE = "data/source/HACK_15_one.ped"  # Data
MAP_FILE = "data/source/HACK_15_one.map"  # Headers
FINAL_FILE = "data/final/ped.csv"  # Resulting csv

from ped_to_csv import ped_to_csv
ped_to_csv(PED_FILE, MAP_FILE, FINAL_FILE)

### First analysis

In [2]:
import pandas as pd

In [3]:
ped = pd.read_csv(FINAL_FILE)

C:\Program Files\Python36\lib\site-packages\IPython\core\interactiveshell.py:2705: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
ped.shape

(5901, 17754)

In [5]:
ped.head()

,id,fid,cos1,cos2,sex,color,rs6599770,rs12440100,rs12906138,rs7179358,...,exm1194798,exm1194803,exm1194806,rs7182651,rs7180058,rs2203349,exm1194810,exm2274791,rs13329121,rs11247329
0,3,19Y384,0,0,2,1,"('A', 'C')","('A', 'G')","('A', 'G')","('A', 'A')",...,"('A', 'A')","('G', 'G')","('C', 'C')","('G', 'G')","('G', 'G')","('T', 'C')","('C', 'C')","('C', 'C')","('T', 'T')","('C', 'T')"
1,4,19Y382,0,0,2,2,"('A', 'C')","('G', 'G')","('A', 'G')","('A', 'A')",...,"('A', 'A')","('G', 'G')","('C', 'C')","('A', 'G')","('G', 'G')","('C', 'C')","('C', 'C')","('C', 'C')","('C', 'T')","('T', 'T')"
2,5,19Y411,0,0,1,2,"('A', 'C')","('G', 'G')","('G', 'G')","('G', 'A')",...,"('A', 'A')","('G', 'G')","('C', 'C')","('A', 'G')","('G', 'G')","('T', 'T')","('T', 'C')","('C', 'C')","('T', 'T')","('C', 'T')"
3,6,19Y406,0,0,2,2,"('C', 'C')","('G', 'G')","('A', 'G')","('G', 'G')",...,"('A', 'A')","('A', 'G')","('C', 'C')","('A', 'G')","('G', 'G')","('T', 'T')","('C', 'C')","('C', 'C')","('T', 'T')","('C', 'T')"
4,7,19Y448,0,0,2,2,"('C', 'C')","('G', 'G')","('G', 'G')","('G', 'G')",...,"('A', 'A')","('G', 'G')","('C', 'C')","('A', 'G')","('G', 'G')","('C', 'C')","('C', 'C')","('C', 'C')","('C', 'T')","('T', 'T')"

In [6]:
ped.groupby('color').count()

,id,fid,cos1,cos2,sex,rs6599770,rs12440100,rs12906138,rs7179358,kgp6444009,...,exm1194798,exm1194803,exm1194806,rs7182651,rs7180058,rs2203349,exm1194810,exm2274791,rs13329121,rs11247329
color,,,,,,,,,,,,,,,,,,,,,
-9,1126,1126,1126,1126,1126,1126,1126,1126,1126,1126,...,1126,1126,1126,1126,1126,1126,1126,1126,1126,1126
1,3011,3011,3011,3011,3011,3011,3011,3011,3011,3011,...,3011,3011,3011,3011,3011,3011,3011,3011,3011,3011
2,1764,1764,1764,1764,1764,1764,1764,1764,1764,1764,...,1764,1764,1764,1764,1764,1764,1764,1764,1764,1764

### Data clearing

In [7]:
# Remove unknown values
ped = ped.drop(ped[ped.color == -9].index)

In [8]:
ped.groupby('color').count()

,id,fid,cos1,cos2,sex,rs6599770,rs12440100,rs12906138,rs7179358,kgp6444009,...,exm1194798,exm1194803,exm1194806,rs7182651,rs7180058,rs2203349,exm1194810,exm2274791,rs13329121,rs11247329
color,,,,,,,,,,,,,,,,,,,,,
1,3011,3011,3011,3011,3011,3011,3011,3011,3011,3011,...,3011,3011,3011,3011,3011,3011,3011,3011,3011,3011
2,1764,1764,1764,1764,1764,1764,1764,1764,1764,1764,...,1764,1764,1764,1764,1764,1764,1764,1764,1764,1764

In [9]:
# Remove not used columns
ped = ped.drop(['id', 'fid', 'cos1', 'cos2', 'sex'], axis=1)

### First useless detection

Here we identify and remove form further analysis polymorphisms that in fact doesn't exists in our data
(one and the same variant for both eyes colors (classes))

In [13]:
# List and remove columns with only one value
useless_poly = []
for poly in list(ped.columns.values):
    if ped[poly].nunique() == 1:
        print(poly)
        useless_poly.append(poly)
        ped = ped.drop(poly, axis=1)

exm1824992
variant.34221
variant.34222
exm1141205
exm1141207
variant.34233
exm1141255
exm1141256
exm1141386
exm1141424
indel.34245
exm1141684
newrs138976716
exm1141701
exm1141908
exm1141919
exm1141954
exm1141981
exm1142007
exm1142468
exm1142570
variant.34264
exm1142579
exm2223088
exm1825714
exm1142692
exm1142700
exm1825749
exm1142770
exm1142780
1KG_15_26260492
variant.34273
indel.34280
exm1142919
rs111782177
rs111864417
rs190819188
rs151210258
rs182290687
rs200732154
rs138228425
rs183101063
rs146505199
rs183743105
rs141949212
rs148894313
variant.34281
rs138335119
rs7173419
rs138985876
rs1800415
rs139844766
rs141159640
rs34141095
rs143699063
rs142152913
exm1143070
exm1143074
rs148413474
rs76026235
rs141627675
exm1143084
rs140566426
rs150020919
exm1143100
rs140703213
exm1143110
rs1800403
rs139743429
rs200651760
rs139562520
rs183487020
rs144175965
rs201791790
rs114097653
rs7496685
rs145385813
rs147271386
rs192999801
rs141739498
rs146332822
rs188787231
rs142779606
exm1143196
rs148731297
rs142354999
rs151325729
rs141203755
rs201971030
rs138594015
rs201003752
rs200336266
rs145413211
rs138341710
rs139713317
rs200993824
rs199500960
rs11854005
rs150956191
exm1143264
rs140708332
rs143291915
rs147450103
rs138275754
rs185562168
rs148628168
rs191221988
rs142169064
exm1143310
rs149707599
rs150131561
rs138827571
rs147059020
rs143832423
rs148365790
rs114532098
rs183106063
rs139346881
rs146210350
rs143963667
rs146521940
rs139953376
rs200121672
rs201578529
rs138954615
rs201933251
rs145438661
rs150517241
rs185547854
rs145190727
rs151256890
rs139335991
rs139973203
rs151122646
rs141457389
rs200931637
rs199850400
rs144426894
rs201136198
rs140167298
rs138960481
rs146366728
rs146159039
rs138887223
rs140027229
rs200651761
rs141969705
rs191942261
rs199647215
rs138059246
rs182540215
rs149498499
rs142615958
rs140060040
rs2905939
rs151115059
rs144780847
rs142034055
rs145481625
rs148823452
rs148050334
exm1143596
rs148787940
rs147519395
rs112385654
rs143710331
rs141847559
rs145594989
rs147535565
rs143130515
rs142553001
rs146777193
exm1143660
rs112230913
rs140345440
rs78460234
rs142950889
exm1143676
rs183120284
exm1143687
rs150675000
rs183596087
rs146056234
rs139718674
rs143948512
rs189875557
rs150992740
rs148362399
rs139846899
rs146191030
rs184405901
rs201936190
rs145043009
rs185860718
rs142149022
rs146210640
rs143576992
rs148005149
rs79860193
rs147680647
rs151331392
rs75131382
exm1144068
exm1144131
exm1144206
exm1144262
exm2223124
variant.34339
exm2223128
indel.34346
exm1144448
indel.34355
exm1144498
indel.34365
newrs146208994
exm1144577
exm1144580
exm1144592
indel.34375
exm1144717
variant.34387
variant.34390
exm1144749
exm1826840
indel.34397
exm1144833
variant.34405
indel.34417
newrs77409359
exm1827016
exm2223146
variant.34422
exm1145196
exm1145208
variant.34423
exm1145219
indel.34428
exm2252105
exm1145299
variant.34436
exm1145319
exm2276365
1KG_15_33200716
exm1145327
indel.34438
exm1145368
exm1145407
indel.34444
indel.34447
exm1145460
indel.34450
exm1145474
rs7179866
indel.34454
variant.34456
exm1145536
exm1145539
exm1145551
exm1145568
exm1145648
exm1827246
exm1145800
exm1145823
exm1145885
exm1827358
exm1145959
exm2223163
exm1145974
1KG_15_34118459
exm1146000
exm1146008
exm1146023
exm1146072
variant.34473
exm1827481
variant.34475
exm1146157
exm1146187
indel.34480
indel.34484
exm1146335
exm1146385
variant.34489
variant.34492
indel.34496
exm1146594
exm1146627
exm1146713
newrs61737329
exm1146717
exm1146744
exm1146865
exm1146945
exm1147045
exm1147170
rs16962788
indel.34527
exm1147248
exm1147314
indel.34535
exm1147338
exm1147498
variant.34544
exm2223183
exm1147537
variant.34546
indel.34552
variant.34553
exm1147691
exm1147720
exm1828317
var_15_39893129
indel.34570
exm1147969
variant.34574
var_15_40284388
variant.34580
exm1148084
variant.34586
exm1148126
exm1148166
variant.34591
indel.34596
exm1148239
var_15_40501902
exm1148307
variant.34621
exm1148552
indel.34637
1KG_15_40628005
variant.34644
exm1148998
exm1149010
exm1149015
variant.34673
exm1149078
variant.34680
exm1149111
exm1149324
exm1149327
exm1149429
exm1149468
exm1149470
exm1149478
exm1149546
exm1149554
exm1149564
exm1149632
exm1149633
exm1149676
indel.34707
rs16970960
exm1149814
exm1149821
exm2223233
variant.34742
exm1150090
exm1150111
exm1150385
exm1150479
exm1150541
variant.34761
variant.34767
indel.34770
var_15_41508995
variant.34774
variant.34781
exm1150740
exm1150772
indel.34787
exm1150798
variant.34789
exm1150966
exm1151020
exm2223250
exm1151081
exm1151087
exm1151101
exm1151109
exm1151154
exm1151214
exm1151240
exm2223257
exm1151356
exm1151461
exm1151532
exm1151597
exm1151688
exm2252142
exm1829782
exm1829815
exm1152047
exm1152222
exm1152530
exm1152653
exm1152911
variant.34950
exm1830147
exm1153335
variant.34979
newrs150082965
variant.34993

KeyboardInterrupt:

In [ ]:
# Shape after first clearing
ped.shape

### Second useless detection

Here we identify and remove form further analysis polymorphisms that in fact doesn't exists in our data
(one and the same variant for both eyes colors (classes))

In [ ]:
#Remove columns with two values where one of them is (0,0)
for poly in list(ped.columns.values):
    if ped[poly].nunique() == 2:
        if "('0', '0')" in ped[poly].unique():
            print(poly, ped[poly].unique())
            useless_poly.append(poly)
            ped = ped.drop(poly, axis=1)

In [58]:
# Shape after second clearing
ped.shape

(4775, 12768)

In [77]:
# Save useless to file
with open("useless_polymorphisms.txt", "w") as f:
    for poly in useless_poly:
        f.write(poly+"\n")

In [78]:
# Store data without useless polymorphisms in 'ped_filtered.csv' file
ped.to_csv("data/finals/ped_filtered.csv")

In [94]:
ped.head()

,rs6599770,rs12440100,rs12906138,rs7179358,kgp6444009,rs4932078,exm1140790,exm1140862,exm1140954,exm1140961,...,exm1194803,rs7182651,rs7180058,rs2203349,exm1194810,exm2274791,rs13329121,rs11247329,sex,color
0,"('A', 'C')","('A', 'G')","('A', 'G')","('A', 'A')","('C', 'A')","('T', 'C')","('A', 'A')","('C', 'C')","('C', 'C')","('G', 'G')",...,"('G', 'G')","('G', 'G')","('G', 'G')","('T', 'C')","('C', 'C')","('C', 'C')","('T', 'T')","('C', 'T')",2,1
1,"('A', 'C')","('G', 'G')","('A', 'G')","('A', 'A')","('C', 'A')","('T', 'C')","('A', 'A')","('C', 'C')","('C', 'C')","('G', 'G')",...,"('G', 'G')","('A', 'G')","('G', 'G')","('C', 'C')","('C', 'C')","('C', 'C')","('C', 'T')","('T', 'T')",2,2
2,"('A', 'C')","('G', 'G')","('G', 'G')","('G', 'A')","('C', 'A')","('T', 'C')","('A', 'A')","('C', 'C')","('C', 'C')","('G', 'G')",...,"('G', 'G')","('A', 'G')","('G', 'G')","('T', 'T')","('T', 'C')","('C', 'C')","('T', 'T')","('C', 'T')",1,2
3,"('C', 'C')","('G', 'G')","('A', 'G')","('G', 'G')","('A', 'A')","('C', 'C')","('G', 'A')","('C', 'C')","('C', 'C')","('G', 'G')",...,"('A', 'G')","('A', 'G')","('G', 'G')","('T', 'T')","('C', 'C')","('C', 'C')","('T', 'T')","('C', 'T')",2,2
4,"('C', 'C')","('G', 'G')","('G', 'G')","('G', 'G')","('A', 'A')","('C', 'C')","('A', 'A')","('C', 'C')","('C', 'C')","('G', 'G')",...,"('G', 'G')","('A', 'G')","('G', 'G')","('C', 'C')","('C', 'C')","('C', 'C')","('C', 'T')","('T', 'T')",2,2